{"request_id": "f1b4cce4-2aea-4c4a-bdc9-9b80749dcc9a", "timestamp": "2025-08-29T07:57:39.567776+00:00", "event_type": "error", "error_type": "ai_analysis_error", "error_message": "AI分析失败: cannot unpack non-iterable coroutine object", "context": {}}
{"request_id": "f1b4cce4-2aea-4c4a-bdc9-9b80749dcc9a", "timestamp": "2025-08-29T07:57:41.308345+00:00", "event_type": "error", "error_type": "ai_analysis_error", "error_message": "AI分析失败: cannot unpack non-iterable coroutine object", "context": {}}
{"request_id": "f1b4cce4-2aea-4c4a-bdc9-9b80749dcc9a", "timestamp": "2025-08-29T07:57:42.232772+00:00", "event_type": "error", "error_type": "ai_analysis_error", "error_message": "AI分析失败: cannot unpack non-iterable coroutine object", "context": {}}
{"request_id": "00132926-6be9-4eab-8f3c-187d625b97d6", "timestamp": "2025-08-29T08:02:43.698463+00:00", "event_type": "error", "error_type": "ai_analysis_error", "error_message": "AI分析失败: HTTPConnectionPool(host='127.0.0.1', port=7897): Max retries exceeded with url: http://104.243.32.173:13333/v1beta/models/gemini-2.5-flash:generateContent?key=sk-Ol7tl792JedgaHkQ0it1jvbHfVddQPIY7zSCoT8frrLruQj8 (Caused by ProxyError('Unable to connect to proxy', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))", "context": {}}
{"request_id": "6631ad96-c659-467f-8cb0-99af12cac605", "timestamp": "2025-08-29T08:04:48.713366+00:00", "event_type": "error", "error_type": "ai_analysis_error", "error_message": "AI分析失败: 'str' object has no attribute 'get'", "context": {}}
{"request_id": "2ea64dd2-230e-43f2-80dc-28d7fc0ea02c", "timestamp": "2025-08-29T08:10:15.174516+00:00", "event_type": "error", "error_type": "ai_analysis_error", "error_message": "AI分析失败: 'str' object has no attribute 'get'", "context": {}}
{"request_id": "da7f6867-cc1f-499a-b23f-2fb98ded6e10", "timestamp": "2025-08-29T08:17:16.005808+00:00", "event_type": "error", "error_type": "ai_analysis_error", "error_message": "AI分析失败: 'str' object has no attribute 'get'", "context": {}}
